// lib/src/features/patients/presentation/pages/create_patient_page.dart

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/base/failure.dart';
import '../../../../core/base/result.dart';
import '../../../../presentation/core/application_state/current_doctor_provider/current_doctor_provider.dart';
import '../../domain/entities/patient_entity.dart';
import '../../patients_providers.dart';
import '../controllers/patients_controller.dart';

class CreatePatientPage extends ConsumerStatefulWidget {
  const CreatePatientPage({super.key, this.existingPatient});

  /// If provided, the page is in edit mode. Otherwise, create mode.
  final PatientEntity? existingPatient;

  @override
  ConsumerState<CreatePatientPage> createState() => _CreatePatientPageState();
}

class _CreatePatientPageState extends ConsumerState<CreatePatientPage> {
  final _formKey = GlobalKey<FormState>();

  final _fullNameController = TextEditingController();
  final _ageController = TextEditingController();
  final _phoneController = TextEditingController();

  String _selectedSex = 'M'; // Default value
  bool _isSaving = false;

  /// Whether we're in edit mode or create mode
  bool get _isEditMode => widget.existingPatient != null;

  @override
  void initState() {
    super.initState();
    // If editing, pre-fill the form with existing data
    if (_isEditMode) {
      final patient = widget.existingPatient!;
      _fullNameController.text = patient.fullName;
      _ageController.text = patient.age.toString();
      _phoneController.text = patient.phone ?? '';
      _selectedSex = patient.sex;
    }
  }

  @override
  void dispose() {
    _fullNameController.dispose();
    _ageController.dispose();
    _phoneController.dispose();
    super.dispose();
  }

  Future<void> _onSavePressed() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _isSaving = true;
    });

    try {
      late Result<PatientEntity, Failure> result;

      if (_isEditMode) {
        // EDIT MODE: Update existing patient
        final updatedPatient = widget.existingPatient!.copyWith(
          fullName: _fullNameController.text.trim(),
          age: int.parse(_ageController.text.trim()),
          sex: _selectedSex,
          phone: _phoneController.text.trim().isEmpty
              ? null
              : _phoneController.text.trim(),
        );

        result = await ref
            .read(patientsControllerProvider.notifier)
            .updatePatient(updatedPatient);
      } else {
        // CREATE MODE: Create new patient
        // Get current doctor ID
        final doctorId = ref.read(currentDoctorIdProvider);

        if (doctorId == null) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Error: No se encontró el ID del doctor.'),
                backgroundColor: Colors.red,
                duration: Duration(seconds: 3),
              ),
            );
          }
          return;
        }

        final patient = PatientEntity(
          id: '', // Will be generated by datasource
          fullName: _fullNameController.text.trim(),
          age: int.parse(_ageController.text.trim()),
          sex: _selectedSex,
          phone: _phoneController.text.trim().isEmpty
              ? null
              : _phoneController.text.trim(),
          doctorId: doctorId,
        );

        result = await ref.read(createPatientUseCaseProvider).call(patient);

        // Refresh list after create
        if (mounted) {
          ref.read(patientsControllerProvider.notifier).refresh();
        }
      }

      // Handle result
      result.when(
        success: (patientData) {
          if (mounted) {
            // Show success message
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(
                  _isEditMode
                      ? 'Paciente actualizado correctamente'
                      : 'Paciente guardado correctamente',
                ),
                backgroundColor: Colors.green,
                duration: const Duration(seconds: 2),
              ),
            );

            // Pop back
            Navigator.of(context).pop();
          }
        },
        error: (failure) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(
                  _isEditMode
                      ? 'Error al actualizar paciente: ${failure.message}'
                      : 'Error al guardar paciente: ${failure.message}',
                ),
                backgroundColor: Colors.red,
                duration: const Duration(seconds: 3),
              ),
            );
          }
        },
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error inesperado: ${e.toString()}'),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 3),
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSaving = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(_isEditMode ? 'Editar paciente' : 'Nuevo paciente'),
      ),
      body: SafeArea(
        child: Form(
          key: _formKey,
          child: ListView(
            padding: const EdgeInsets.all(16),
            children: [
              // Full Name Field
              TextFormField(
                controller: _fullNameController,
                decoration: const InputDecoration(
                  labelText: 'Nombre completo',
                  hintText: 'Ej: María López Hernández',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.person),
                ),
                textInputAction: TextInputAction.next,
                textCapitalization: TextCapitalization.words,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'El nombre es requerido';
                  }
                  if (value.trim().length < 3) {
                    return 'El nombre debe tener al menos 3 caracteres';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Age Field
              TextFormField(
                controller: _ageController,
                decoration: const InputDecoration(
                  labelText: 'Edad',
                  hintText: 'Ej: 28',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.cake),
                  suffixText: 'años',
                ),
                keyboardType: TextInputType.number,
                inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                textInputAction: TextInputAction.next,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'La edad es requerida';
                  }
                  final age = int.tryParse(value.trim());
                  if (age == null) {
                    return 'Ingrese un número válido';
                  }
                  if (age <= 0 || age > 150) {
                    return 'La edad debe estar entre 1 y 150';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Sex Dropdown
              DropdownButtonFormField<String>(
                value: _selectedSex,
                decoration: const InputDecoration(
                  labelText: 'Sexo',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.wc),
                ),
                items: const [
                  DropdownMenuItem(value: 'M', child: Text('Masculino')),
                  DropdownMenuItem(value: 'F', child: Text('Femenino')),
                  DropdownMenuItem(value: 'Otro', child: Text('Otro')),
                ],
                onChanged: (value) {
                  if (value != null) {
                    setState(() {
                      _selectedSex = value;
                    });
                  }
                },
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'El sexo es requerido';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Phone Field (Optional)
              TextFormField(
                controller: _phoneController,
                decoration: const InputDecoration(
                  labelText: 'Teléfono (opcional)',
                  hintText: 'Ej: 555-123-4567',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.phone),
                ),
                keyboardType: TextInputType.phone,
                textInputAction: TextInputAction.done,
                validator: (value) {
                  // Phone is optional
                  if (value == null || value.trim().isEmpty) {
                    return null;
                  }

                  // Basic phone validation if provided
                  final phone = value.trim();
                  if (phone.length < 7) {
                    return 'El teléfono debe tener al menos 7 caracteres';
                  }

                  return null;
                },
              ),
              const SizedBox(height: 24),

              // Info card
              Card(
                color: theme.colorScheme.primaryContainer.withOpacity(0.3),
                child: Padding(
                  padding: const EdgeInsets.all(12),
                  child: Row(
                    children: [
                      Icon(
                        Icons.info_outline,
                        color: theme.colorScheme.primary,
                        size: 20,
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          'El paciente será asignado automáticamente al doctor actual.',
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: theme.colorScheme.onSurface.withOpacity(0.7),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),

              // Save Button
              SizedBox(
                width: double.infinity,
                child: FilledButton.icon(
                  onPressed: _isSaving ? null : _onSavePressed,
                  icon: _isSaving
                      ? const SizedBox(
                          width: 18,
                          height: 18,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Icon(Icons.save),
                  label: Text(
                    _isSaving
                        ? (_isEditMode ? 'Actualizando...' : 'Guardando...')
                        : (_isEditMode
                              ? 'Guardar cambios'
                              : 'Guardar paciente'),
                  ),
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
